name: Go Stream Build Actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        mkdir -p dist
        # 构建主程序（替换为您的实际包路径）
        go build -o dist/go-stream ./

    - name: Test
      run: go test -v ./...

    - name: Package Artifacts
      run: |
        # 使用提交信息生成文件名
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)
        FILENAME="go-stream-${TIMESTAMP}-${COMMIT_SHA_SHORT}.tar.gz"
        
        tar czvf "$FILENAME" dist/*
        mkdir release-artifacts
        mv "$FILENAME" release-artifacts/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-stream-binaries
        path: release-artifacts/
        retention-days: 7  # 设置保留天数（默认90天）
