name: Go Stream Actions

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]  # 添加tags触发条件
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        # 构建二进制文件并放入dist目录
        mkdir -p dist
        go build -o dist/go-stream ./   # 替换myapp为你的应用名称

    - name: Test
      run: go test -v ./...

    - name: Package Artifacts
      run: |
        tar czvf release.tar.gz dist/  # 打包dist目录
        mkdir release-artifacts
        mv release.tar.gz release-artifacts/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: release-artifacts/

  release:
    needs: build  # 依赖build任务
    if: startsWith(github.ref, 'refs/tags/')  # 仅在tag推送时触发
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-package
          path: release-files

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-files/*  # 发布所有打包文件
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用内置token
