name: Go Stream Build Actions

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]  # 添加tags触发条件
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        # 修复：为每个主包单独构建
        mkdir -p dist
        # 构建主程序（替换为您的实际包路径）
        go build -o dist/go-stream ./
        GOOS=linux GOARCH=amd64 go build -o dist/go-stream-linux-amd64 ./
        GOOS=windows GOARCH=amd64 go build -o dist/go-stream-windows-amd64.exe ./

    - name: Test
      run: go test -v ./...

    - name: Package Artifacts
      run: |
        # 创建带版本号的压缩包
        VERSION=${GITHUB_REF#refs/tags/}
        tar czvf "go-stream-$VERSION-linux-amd64.tar.gz" dist/*
        mkdir release-artifacts
        mv *.tar.gz release-artifacts/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: release-artifacts/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-package
          path: release-files

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-files/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
